### ISSUE TITLE
WiiU freezes after playing for half an hour

### ISSUE THREAD

**Issue by SD-CD** [Crayon2000/UsendMii-Client#31] opened 2024-11-10 06:06 UTC
I am on the aroma environment and I downloaded this on the homebrew app store if that helps. I checked my sd card and both the .wuhb and .rpx versions of MiiSendU are installed on it. I have to manually turn off my wii u console then turn it back on each time the wii u gamepad freezes.

**Comment by Awesome-guyy** [comment] 2024-11-12 01:22
I have the same issue here.

**Comment by Crayon2000** [comment] 2024-12-17 06:09
Duplicate of #25

**Closed as not planned by Crayon2000** 2024-12-17 06:09 UTC
Labels: duplicate
