### ISSUE TITLE
WiiU Freezing after 30-ish minute of use

### ISSUE THREAD

**Issue by SpritBit** [Crayon2000/UsendMii-Client#25] opened 2024-05-03 19:01 UTC
i use MiisendU everyday since i dont have a controller, but recently i found an issue, every 30-ish minutes, my wii u freezes and i have to unplug it and replug it and go to the app and type my IP adresse again and its kinda annoying, i asked on reddit though no one responded. this didnt happen on my old wii u so why the hell is it happening on this one? the only differences between them is that the one im using rn is a basic build (the white 8GB Wii U) while my old one was a deluxe build (the black 32GB Wii U)

**Comment by Crayon2000** [comment] 2024-05-03 19:04
Thanks for reporting the problem. I'll try to look at it whenever I have time.

**Comment by Crayon2000** [comment] 2024-05-13 05:03
Hello, I just want to tell you I was able to reproduce the problem using the _.rpx_ version. The _.wuhb_ with aroma seems to be working properly.

**Comment by SD-CD** [comment] 2024-11-09 06:35
I also am having this problem. I checked my sd card and both the .wuhb and .rpx are installed on it. I am on aroma environment. I downloaded this on the homebrew app store if that helps.

**Comment by SD-CD** [comment] 2024-12-17 06:12
> Hello, I just want to tell you I was able to reproduce the problem using the _.rpx_ version. The _.wuhb_ with aroma seems to be working properly.

I downloaded this off of the homebrew app store. It contains both the .wuhb and .rpx version, but I believe I need both for it to work properly.

**Comment by Crayon2000** [comment] 2024-12-17 06:13
I think I found the problem. I guess there is a leak in the JSON parsing code. I will try to fix that during the holidays.
By the way, I think the version in the master branch takes now around an hour before it stops sending data.

**Comment by Crayon2000** [comment] 2024-12-26 21:32
Fixed in PR #32

**Closed as completed by Crayon2000** 2024-12-26 21:32 UTC
Labels: bug
